version: "3.6"
networks:
  back:
services:
  prod:
    image: ghcr.io/donetsk-dev/webapp_dnr.dev:alpha
    ports:
      - 3000:3000
    networks:
      - back
  alpha:
    image: ghcr.io/donetsk-dev/webapp_dnr.dev:alpha
    ports:
      - 3001:3000
    networks:
      - back


